services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.websecure.address=:443'
      - '--entrypoints.websecure.http3'
      - '--certificatesresolvers.caccabotresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.caccabotresolver.acme.email=caccabot@proton.me'
      - '--certificatesresolvers.caccabotresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--accesslog=true'
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true
    deploy:
      update_config:
        order: start-first

  caccabot:
    image: ghcr.io/caccabot/caccabot:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.caccabot.rule=Host(`caccabot.duckdns.org`)'
      - 'traefik.http.routers.caccabot.entrypoints=websecure'
      - 'traefik.http.routers.caccabot.tls.certresolver=caccabotresolver'
      - 'traefik.http.services.caccabot.loadbalancer.server.scheme=h2c'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'traefik.http.middlewares.test-compress.compress.defaultEncoding=zstd'
    volumes:
      - /home/ubuntu/caccabot_data/storage:/app/storage/
      - /home/ubuntu/caccabot_data/wwebjs_auth:/app/.wwebjs_auth
      - /home/ubuntu/caccabot_data/wwebjs_cache:/app/.wwebjs_cache
      - /home/ubuntu/caccabot_data/pfp:/app/public/pfp
      - /home/ubuntu/caccabot_data/config_prod.json:/app/config/config_prod.json
    environment:
      - ENVIRONMENT=production
      - SERVER_PORT=3000
    deploy:
      update_config:
        order: start-first
    ports:
      - '3000:3000'
    expose:
      - '3000'

volumes:
  caccabot_data:
  letsencrypt:
